# UCS420 - Cognitive Computing
## NumPy Assignment - 1
**Name:** Kashish Singhal

In [ ]:
import numpy as np

## Q1. 1D NumPy array with 5 elements and basic operations

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)

Original array: [10 20 30 40 50]


In [ ]:
print("a) Addition of 2:", arr + 2)

a) Addition of 2: [12 22 32 42 52]


In [ ]:
print("b) Multiply by 3:", arr * 3)

b) Multiply by 3: [ 30  60  90 120 150]


In [ ]:
print("c) Divide by 2:", arr / 2)

c) Divide by 2: [ 5. 10. 15. 20. 25.]


## Q2. Basic NumPy Array Operations

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("a) Reversed array:", arr[::-1])

a) Reversed array: [5 4 6 3 2 1]


In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

vals, counts = np.unique(x, return_counts=True)
most_freq = vals[np.argmax(counts)]
indices = np.where(x == most_freq)[0]

print("b i) Array x:", x)
print("Most frequent value:", most_freq)
print("Indices:", indices)

b i) Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Indices: [0 5 7 8 9]


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

vals, counts = np.unique(y, return_counts=True)
most_freq = vals[np.argmax(counts)]
indices = np.where(y == most_freq)[0]

print("b ii) Array y:", y)
print("Most frequent value:", most_freq)
print("Indices:", indices)

b ii) Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Indices: [0 1 2]


## Q3. 2D Array - Accessing Elements

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2D Array:")
print(arr)

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
print("a) 1st row, 2nd column:", arr[0, 1])

a) 1st row, 2nd column: 20


In [ ]:
print("b) 3rd row, 1st column:", arr[2, 0])

b) 3rd row, 1st column: 70


## Q4. linspace() - Array Properties and Transpose

In [ ]:
Kashish Singhal = np.linspace(10, 100, 25)
print("Array:", Kashish Singhal)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
print("Dimensions (ndim):", Kashish Singhal.ndim)
print("Shape:", Kashish Singhal.shape)
print("Total elements (size):", Kashish Singhal.size)
print("Data type:", Kashish Singhal.dtype)
print("Total bytes:", Kashish Singhal.nbytes)

Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type: float64
Total bytes: 200


In [ ]:
transposed_reshape = Kashish Singhal.reshape(25, 1)
print("Transpose using reshape():")
print(transposed_reshape)

Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [ ]:
print("Transpose using .T attribute:")
print(Kashish Singhal.T)
print()
print("For a 1D array, .T does not change anything since there's only one dimension.")
print("We need to first reshape it to 2D to see any effect with .T")
print()
reshaped_2d = Kashish Singhal.reshape(1, 25)
print("After reshape to (1,25), transpose using .T:")
print(reshaped_2d.T)

Transpose using .T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

For a 1D array, .T does not change anything since there's only one dimension.
We need to first reshape it to 2D to see any effect with .T

After reshape to (1,25), transpose using .T:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


## Q5. 2D Array - Statistics, Reshape, Resize

In [ ]:
ucs420_Kashish Singhal = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("ucs420_Kashish Singhal:")
print(ucs420_Kashish Singhal)

ucs420_Kashish Singhal:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


In [ ]:
print("Mean:", np.mean(ucs420_Kashish Singhal))
print("Median:", np.median(ucs420_Kashish Singhal))
print("Max:", np.max(ucs420_Kashish Singhal))
print("Min:", np.min(ucs420_Kashish Singhal))
print("Unique elements:", np.unique(ucs420_Kashish Singhal))

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [ ]:
reshaped_ucs420_Kashish Singhal = ucs420_Kashish Singhal.reshape(4, 3)
print("Reshaped to (4x3):")
print(reshaped_ucs420_Kashish Singhal)

Reshaped to (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [ ]:
resized_ucs420_Kashish Singhal = np.resize(ucs420_Kashish Singhal, (2, 3))
print("Resized to (2x3):")
print(resized_ucs420_Kashish Singhal)

Resized to (2x3):
[[10 20 30]
 [40 50 60]]
