# UCS420 - Cognitive Computing
## Assignment 6 — NumPy II
**Name:** Kashish Singhal

In [1]:
import numpy as np

## Q1. Sensor Readings - Vectorization and Boolean Indexing

In [2]:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print("Original readings:", temperature)

Original readings: [25 28 31 35 38 27 33 40]


In [3]:
corrected = temperature + 2
print("a) After adding 2 degree correction:", corrected)

a) After adding 2 degree correction: [27 30 33 37 40 29 35 42]


In [4]:
fahrenheit = (9/5) * temperature + 32
print("b) Celsius to Fahrenheit:", fahrenheit)

b) Celsius to Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]


In [5]:
above_32 = temperature[temperature > 32]
print("c) Readings greater than 32C:", above_32)

c) Readings greater than 32C: [35 38 33 40]


In [6]:
count = np.sum(temperature > 32)
print("d) Number of readings exceeding 32C:", count)

d) Number of readings exceeding 32C: 4


**e) Vectorization vs Looping:**

With a regular for loop, Python processes one element at a time which means a lot of overhead for each iteration. Vectorization in NumPy applies the operation to the entire array at once using optimized C code internally, so it's much faster especially as array size grows.

Boolean indexing works the same way — instead of checking each element with an if statement inside a loop, NumPy creates a boolean mask for the whole array in one go and uses it to filter values. For large datasets like real sensor streams, this difference in speed is very noticeable.

## Q2. Daily Steps Matrix - Aggregation and Axis Operations

In [7]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
print("Steps matrix:")
print(steps)

Steps matrix:
[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]


In [8]:
print("a) Total steps recorded:", np.sum(steps))

a) Total steps recorded: 84200


In [9]:
print("b) Mean steps:", np.mean(steps))

b) Mean steps: 7016.666666666667


In [10]:
print("c) Maximum value:", np.max(steps))
print("   Minimum value:", np.min(steps))

c) Maximum value: 9500
   Minimum value: 4500


In [11]:
print("d) Total steps per day (axis=0):", np.sum(steps, axis=0))

d) Total steps per day (axis=0): [26500 27300 30400]


In [12]:
print("e) Total steps per user (axis=1):", np.sum(steps, axis=1))

e) Total steps per user (axis=1): [18300 24500 14400 27000]


In [13]:
flat_idx = np.argmax(steps)
row, col = np.unravel_index(flat_idx, steps.shape)
print("f) Position of maximum steps -> User (row):", row, ", Day (col):", col)
print("   Value at that position:", steps[row, col])

f) Position of maximum steps -> User (row): 3 , Day (col): 2
   Value at that position: 9500


## Q3. Slicing, Copying, Reshaping and Flattening

In [14]:
original = np.array([1, 2, 3, 4, 5, 6])
print("a) Original array:", original)

a) Original array: [1 2 3 4 5 6]


In [15]:
subset = original[1:5]
print("b) Subset (index 1 to 4):", subset)

b) Subset (index 1 to 4): [2 3 4 5]


In [16]:
subset[0] = 999
print("c) After modifying subset[0] to 999:")
print("   subset:", subset)
print("   original:", original)
print("   (original also changed because subset is a view, not a copy)")

c) After modifying subset[0] to 999:
   subset: [999   3   4   5]
   original: [  1 999   3   4   5   6]
   (original also changed because subset is a view, not a copy)


In [17]:
original = np.array([1, 2, 3, 4, 5, 6])
copied = original[1:5].copy()
copied[0] = 500
print("d) After modifying copied[0] to 500:")
print("   copied array:", copied)
print("   original array:", original)
print("   (original is unchanged because .copy() creates an independent array)")

d) After modifying copied[0] to 500:
   copied array: [500   3   4   5]
   original array: [1 2 3 4 5 6]
   (original is unchanged because .copy() creates an independent array)


In [18]:
matrix = np.arange(1, 13).reshape(3, 4)
print("e) 3x4 matrix using arange and reshape:")
print(matrix)

e) 3x4 matrix using arange and reshape:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
print("f) Slicing operations:")
print("   First row:", matrix[0, :])
print("   Last row:", matrix[-1, :])
print("   Second column:", matrix[:, 1])
print("   Rows 1-2, Columns 2-3:")
print(matrix[1:3, 2:4])

f) Slicing operations:
   First row: [1 2 3 4]
   Last row: [ 9 10 11 12]
   Second column: [ 2  6 10]
   Rows 1-2, Columns 2-3:
[[ 7  8]
 [11 12]]


In [20]:
flat_flatten = matrix.flatten()
flat_ravel = matrix.ravel()
print("g) flatten():", flat_flatten)
print("   ravel(): ", flat_ravel)

g) flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
   ravel():  [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
flat_ravel[0] = 999
print("h) After modifying ravel()[0] to 999:")
print("   ravel array:", flat_ravel)
print("   original matrix:")
print(matrix)
print("   (ravel() returns a view so the original matrix is also changed)")

h) After modifying ravel()[0] to 999:
   ravel array: [999   2   3   4   5   6   7   8   9  10  11  12]
   original matrix:
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
   (ravel() returns a view so the original matrix is also changed)


In [22]:
matrix = np.arange(1, 13).reshape(3, 4)
flat_flatten = matrix.flatten()
flat_flatten[0] = 500
print("i) After modifying flatten()[0] to 500:")
print("   flattened array:", flat_flatten)
print("   original matrix:")
print(matrix)
print("   (flatten() returns a copy so the original is not affected)")

i) After modifying flatten()[0] to 500:
   flattened array: [500   2   3   4   5   6   7   8   9  10  11  12]
   original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
   (flatten() returns a copy so the original is not affected)


In [23]:
matrix = np.arange(1, 13).reshape(3, 4)
print("j) Properties of the 3x4 matrix:")
print("   shape:", matrix.shape)
print("   ndim:", matrix.ndim)
print("   size:", matrix.size)
print("   dtype:", matrix.dtype)

j) Properties of the 3x4 matrix:
   shape: (3, 4)
   ndim: 2
   size: 12
   dtype: int64


## Q4. Cognitive Assistive System - OLS Regression using NumPy

In [24]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("a) Shape of X:", X.shape)
print("   Dimensions of X:", X.ndim)

a) Shape of X: (4, 3)
   Dimensions of X: 2


In [25]:
print("b) Transpose of X (X.T):")
print(X.T)
print()
print("The transpose flips rows and columns. Original X has shape (4,3) meaning 4 users x 3 features.")
print("X.T has shape (3,4) — each row now represents one feature across all 4 users.")
print("This is needed for matrix multiplication in OLS.")

b) Transpose of X (X.T):
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

The transpose flips rows and columns. Original X has shape (4,3) meaning 4 users x 3 features.
X.T has shape (3,4) — each row now represents one feature across all 4 users.
This is needed for matrix multiplication in OLS.


In [26]:
XtX = X.T @ X
print("c) X.T @ X:")
print(XtX)

c) X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [27]:
XtX_inv = np.linalg.inv(XtX)
print("d) Inverse of (X.T @ X):")
print(XtX_inv)

d) Inverse of (X.T @ X):
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


In [28]:
beta = XtX_inv @ X.T @ y
print("e) OLS coefficients (beta = (X.T X)^-1 X.T y):")
print(beta)

e) OLS coefficients (beta = (X.T X)^-1 X.T y):
[-0.15921454  0.14083853 10.06302242]


**f) What the coefficients mean:**

Each coefficient in `beta` tells us how much the assistance score changes for a one-unit increase in that feature, keeping the other two constant.

- **beta[0]** → effect of Sleep hours on assistance score
- **beta[1]** → effect of Activity level on assistance score  
- **beta[2]** → effect of Stress level on assistance score

A negative coefficient for sleep/activity would mean higher values lower the score (less assistance needed), and a positive coefficient for stress would mean higher stress raises the score (more assistance needed). The exact direction depends on the computed values.

In [29]:
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("g) New user features:", new_user)
print("   Predicted assistance score:", round(predicted_score, 2))

g) New user features: [ 5 40  7]
   Predicted assistance score: 75.28
